### ISSUE TITLE
Possible 'this.' mis-test

### ISSUE THREAD

**Issue by OvermindDL1** [wojtekmach/oop#3]
If the user has some variable named something like `blahthis` and they access something on it like `blahthis.something`, then https://github.com/wojtekmach/oop/blob/master/lib/oop.ex#L105 looks like it would capture it.  Putting a `\b` at the start of the regex to only match on a word bound should fix it I think?

**Comment by wojtekmach** [comment]
good catch :) yeah, using word boundary in the regexp should do it. Another option is to traverse the "method" ast searching for `this`.
