### ISSUE TITLE
Links section in README

### ISSUE THREAD

**Issue by ponyatov** [wojtekmach/oop#8]
I'm going to write some sort of object database works over the BEAM machine for storing and manipulating large source code conglomerates (for legacy analysis and raking, stored in preparsed AST-like graphs). The way I select to represent such alike data is object graphs, so I need some info on how to implement OOP-related mechanics over the BEAM virtual machine.

Could you provide the Links section in your project points to some manuals that can be used to understand your source code and methods you are using?

**Comment by wojtekmach** [comment]
This project is a joke and there was no consideration around performance etc, so I wouldn’t even look at the source code. There were real attempts at OOP on BEAM, eg earliest version of Elixir, so I’d instead look there. I believe most if not all attempts failed. Good luck with your research!
